name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your main branch has a different name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full repository history is available

      # If you need to build your site, add a build step here.
      # For a simple static site, no build is required.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./frontend  # Folder to deploy
          publish_branch: gh-pages  # Branch where the site will be published
